[tool.mypy]

[[tool.mypy.overrides]]
module = "boto3.*"
ignore_missing_imports = true

[tool.pytest]

[tool.pylint.messages_control]
max-line-length = 88
disable = [
  "C",
  "R",
  "no-name-in-module",
  "fixme",
  "unspecified-encoding",
]
